[workspace]
members = ["day-*", "template"]

[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.21", features = ["derive"] }
day-01 = { version = "0.1.0", path = "day-01" }
dhat = "0.3.3"
tracing = { workspace = true }

[workspace.dependencies]
nom = "7.1.3"
tracing = "0.1.41"

[profile.dhat]
inherits = "release"
debug = 1

[features]
dhat-heap = []
