[package]
name = "grid"
version = "0.1.0"
edition = "2021"
rust-version = "1.83.0"

[dependencies]
divan = { workspace = true, optional = true }

[features]
bench = ["dep:divan"]

[[bench]]
name = "benchmark"
harness = false
